### PR TITLE
Feature dev

### PR DESCRIPTION
**Pull request by abongsjoel**
This is the first pull request and we have worked on the following elements:

Navigation bar

It has an embedded image that represents a logo.
The logo is aligned to the leftmost part of the navbar.
It has an input tag that represents a search bar.
The search bar is aligned to the middle of the navbar.
It has a button tag that represents the search button.
The search button is at the end (rightmost part) of the search bar.
It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar.

Video

It is displayed.
It shows the video title.
It shows the number of views.
It has like and dislike icons.
It has a share button.
It shows the avatar of the user who uploaded the video.
It has a subscribe button.

Sidebar Recommended videos 

It shows the recommended video’s thumbnail preview (as image not as an actual video).
It shows the title of the video.
It shows the number of views.

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @ . Thanks for submitting you project!

Great thing this project has and has done well:
:100: It has the logo as an embedded image, in the left space of navbar
:100: it has a search bar in the middle that uses `<input>` tag for the input.
:100: the navbar follows the original website design
:100: it has a video section, that can be reproduced, that shows the title, the number of views, and the like/dislike buttons, it shows an avatar image and a subscribe button.
:100: it has a recommended video section, that shows the title and the number of views.
:100: each section has its own container

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The search button in the navbar should be an actual `<button>`.

- [ ] The recommended videos section is not displaying the video thumbnails.
image

- [ ] Use [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) `<aside>` tag for the recommended videos section

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle: 
### Hello Team! 
 
### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

 **General**



- [ ] Your project looks great. However, your project cannot be approved until you write a descriptive Pull Request Message. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

**Mandatory**
- [ ] The recommended videos section is not displaying the video thumbnails.( [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_thumbnail_requirement.png) form [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/) )


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review @tamara._ :wink: 
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hello Team! 

### Thank you for making the required changes! Your project is approved!  Keep up the good work 💯  :clap: :clap: :clap: :tada:

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by ahzia** [comment]
Congratulations on your first project!

**Pull request merged**
